apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tlsPort }}
      targetPort: {{ .Values.service.tlsPort }}
      protocol: UDP
      name: {{ include "coturn.fullname" . }}-tls-port1
    - port: {{ .Values.service.tlsPort }}
      targetPort: {{ .Values.service.tlsPort }}
      protocol: TCP
      name: {{ include "coturn.fullname" . }}-tls-port2
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
